### ISSUE TITLE
Repo title

### ISSUE THREAD

**Issue by tanohzana** [reacli/cli-docs#1]
Hello, is it possible to name the repo `www` or `website`, or anything else that says it's a website or a landing page, as it is not a `documentation` page, but rather an `advertising` page, in my opinion. If we were to simply create a doc, then we would just give people the link to our `README.md`... Which we are not trying to do, so let's be more open to the world, and not to devs only. This, in my opinion, is not a `documentation` page/site.

What do you think ?

**Comment by gdarchen** [comment]
The name of the repository is what will be the base name of the website's URL... Naming it `www` would cause the URL to be quite strange...isn't it ? Would `http://reacli.github.io/website` be suitable for you ?

Changing the repository name also implies to modify the Github Pages URL in the `package.json`.

**Comment by tanohzana** [comment]
Any way we can have just `http://reacli.github.io` ?

**Comment by gdarchen** [comment]
To do so, we have to create a repository named `reacli.github.io` and post on its `master` branch the bundled code... So what I propose is to keep having the `cli-docs` repository to keep the sources and create a `reacli.github.io` repository for the bundles and the Organization Page. Would that suit you ?

**Comment by tanohzana** [comment]
It sounds complicated, just for a landing page ;-) don't worry, go with what you think is the best, but let's keep it to one repo regarding the landing page. I think it would be easy to just decide what name the repo would take and how it could be accessed... By anyway... I trust your judgement on this.

**Comment by gdarchen** [comment]
It should be solved thanks to PR #3.
